# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: request.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrequest.proto\x12\x04TSPO\x1a\x1bgoogle/protobuf/empty.proto\",\n\nCoordinate\x12\x0e\n\x06\x63oordX\x18\x01 \x01(\x01\x12\x0e\n\x06\x63oordY\x18\x02 \x01(\x01\"l\n\x13OptimizationRequest\x12%\n\x0b\x63oordinates\x18\x01 \x03(\x0b\x32\x10.TSPO.Coordinate\x12\x14\n\x0cmutationRate\x18\x02 \x01(\x01\x12\x18\n\x10individualNumber\x18\x03 \x01(\x05\"L\n\x11OptimizationReply\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12%\n\x0b\x63oordinates\x18\x02 \x03(\x0b\x32\x10.TSPO.Coordinate\";\n\x12UpdateNotification\x12%\n\x0b\x63oordinates\x18\x01 \x03(\x0b\x32\x10.TSPO.Coordinate2\x8e\x01\n\x0cOptimization\x12@\n\x08Optimize\x12\x19.TSPO.OptimizationRequest\x1a\x17.TSPO.OptimizationReply\"\x00\x12<\n\x06Update\x12\x18.TSPO.UpdateNotification\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COORDINATE']._serialized_start=52
  _globals['_COORDINATE']._serialized_end=96
  _globals['_OPTIMIZATIONREQUEST']._serialized_start=98
  _globals['_OPTIMIZATIONREQUEST']._serialized_end=206
  _globals['_OPTIMIZATIONREPLY']._serialized_start=208
  _globals['_OPTIMIZATIONREPLY']._serialized_end=284
  _globals['_UPDATENOTIFICATION']._serialized_start=286
  _globals['_UPDATENOTIFICATION']._serialized_end=345
  _globals['_OPTIMIZATION']._serialized_start=348
  _globals['_OPTIMIZATION']._serialized_end=490
# @@protoc_insertion_point(module_scope)
