version: "3.8"

services:
  tsp_backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: tsp_backend
    networks:
      - tsp_network
    ports:
      - "50051:50051"

  tsp_frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: tsp_frontend
    networks:
      - tsp_network
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "50052:50052"
    stdin_open: true     # Same as -it
    tty: true            # Same as -it

networks:
  tsp_network:
    driver: bridge
